import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { sha256Hex } from '@skillcheck/core';
import { headlineSentence } from '../src/headline';

// Verifies the COMMITTED site data is internally consistent — its run-meta checksums match
// the actual skills.json / findings.json bytes, proving the published data was generated by
// the pipeline and not hand-edited (DoD: publish output checksum-verified against site data).
const DATA = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'site', 'src', 'data');
const skillsJson = readFileSync(join(DATA, 'skills.json'), 'utf8');
const findingsJson = readFileSync(join(DATA, 'findings.json'), 'utf8');
const runMeta = JSON.parse(readFileSync(join(DATA, 'run-meta.json'), 'utf8'));

describe('committed site data', () => {
  it('run-meta checksums match the emitted JSON byte-for-byte', () => {
    expect(runMeta.checksums.skills_json).toBe(sha256Hex(skillsJson));
    expect(runMeta.checksums.findings_json).toBe(sha256Hex(findingsJson));
  });

  it('skills.json is a well-formed array with the published schema', () => {
    const skills = JSON.parse(skillsJson);
    expect(Array.isArray(skills)).toBe(true);
    expect(skills.length).toBe(runMeta.cohort.gradedCount);
    for (const s of skills) {
      expect(s).toHaveProperty('id');
      expect(s).toHaveProperty('safety');
      expect(s.effectiveness).toBe('not_yet_benchmarked');
      expect(s.honesty).toBe('not_yet_benchmarked');
    }
  });

  it('no gated skill leaks identifiers (anonymized rows carry no repo/name)', () => {
    const skills = JSON.parse(skillsJson) as { anonymized: boolean; repo: string | null; name: string | null }[];
    for (const s of skills.filter((x) => x.anonymized)) {
      expect(s.repo).toBeNull();
      expect(s.name).toBeNull();
    }
  });

  it('headline generator produces a sentence from the published metadata', () => {
    const sentence = headlineSentence(runMeta);
    expect(sentence).toMatch(/^I scanned .+: /);
    expect(sentence).toContain(`${headlinePct(runMeta.headline.injection)}% carry prompt-injection`);
  });
});

function headlinePct(s: { numerator: number; denominator: number }): string {
  return s.denominator === 0 ? '0' : (Math.round((10000 * s.numerator) / s.denominator) / 100).toString();
}
